import { nanoid } from "nanoid";
import type { Trip } from "@/lib/types";

export function createDemoTrip(): Trip {
  const now = new Date();

  return {
    id: "demo-trip",
    title: "Rome & Florence Adventure",
    description: "A week exploring the best of Italy",
    destination: {
      city: "Rome",
      country: "Italy",
    },
    timezone: "Europe/Rome",
    createdAt: now,
    updatedAt: now,
    unassignedCards: [
      {
        id: nanoid(),
        type: "activity",
        title: "Visit the Spanish Steps",
        notes: "Great photo opportunity",
        tags: ["optional", "photo-op"],
        links: [],
        status: "pending" as const,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: nanoid(),
        type: "meal",
        title: "Try authentic carbonara",
        notes: "Find a local trattoria recommendation",
        tags: ["food", "must-try"],
        links: [],
        status: "pending" as const,
        createdAt: now,
        updatedAt: now,
      },
    ],
    days: [
      {
        id: nanoid(),
        date: "2024-11-15",
        title: "Arrival in Rome",
        cards: [
          {
            id: nanoid(),
            type: "transit",
            title: "Flight to Rome (FCO)",
            startTime: "08:00",
            endTime: "14:30",
            duration: 390,
            notes: "United flight UA123. Terminal 5.",
            tags: ["flight", "international"],
            links: ["https://united.com/confirmation"],
            status: "confirmed" as const,
            createdAt: now,
            updatedAt: now,
          },
          {
            id: nanoid(),
            type: "transit",
            title: "Airport transfer to hotel",
            startTime: "15:00",
            duration: 45,
            location: {
              name: "Hotel Artemide",
              address: "Via Nazionale, 22, 00184 Roma",
            },
            cost: {
              amount: 50,
              currency: "EUR",
            },
            notes: "Pre-booked shuttle. Confirmation #ROM-45782",
            tags: ["transfer", "booked"],
            links: [],
            status: "confirmed" as const,
            createdAt: now,
            updatedAt: now,
          },
          {
            id: nanoid(),
            type: "meal",
            title: "Dinner at Trattoria Monti",
            startTime: "19:30",
            duration: 120,
            location: {
              name: "Trattoria Monti",
              address: "Via di San Vito, 13A, 00185 Roma",
            },
            cost: {
              amount: 80,
              currency: "EUR",
            },
            notes: "Reservation for 2. Amazing pasta!",
            tags: ["reservation", "must-try"],
            links: ["https://maps.google.com/..."],
            status: "confirmed" as const,
            createdAt: now,
            updatedAt: now,
          },
        ],
      },
      {
        id: nanoid(),
        date: "2024-11-16",
        title: "Ancient Rome",
        cards: [
          {
            id: nanoid(),
            type: "meal",
            title: "Breakfast at hotel",
            startTime: "08:00",
            duration: 45,
            notes: "Included with stay",
            tags: ["included"],
            links: [],
            status: "pending" as const,
            createdAt: now,
            updatedAt: now,
          },
          {
            id: nanoid(),
            type: "activity",
            title: "Colosseum & Roman Forum Tour",
            startTime: "09:00",
            endTime: "13:00",
            duration: 240,
            location: {
              name: "Colosseum",
              address: "Piazza del Colosseo, 1, 00184 Roma",
            },
            cost: {
              amount: 65,
              currency: "EUR",
            },
            notes:
              "Skip-the-line tickets booked. Tour starts at 9 AM sharp. Bring water!",
            tags: ["ticket-booked", "priority", "must-see"],
            links: [
              "https://parcocolosseo.it/en/",
              "https://confirmation.email",
            ],
            status: "confirmed" as const,
            createdAt: now,
            updatedAt: now,
          },
          {
            id: nanoid(),
            type: "meal",
            title: "Lunch near Forum",
            startTime: "13:30",
            duration: 60,
            notes: "Find a spot with outdoor seating",
            tags: [],
            links: [],
            status: "pending" as const,
            createdAt: now,
            updatedAt: now,
          },
          {
            id: nanoid(),
            type: "activity",
            title: "Pantheon visit",
            startTime: "15:00",
            duration: 60,
            location: {
              name: "Pantheon",
              address: "Piazza della Rotonda, 00186 Roma",
            },
            notes: "Free entry. Best time is afternoon.",
            tags: ["free", "must-see"],
            links: [],
            status: "pending" as const,
            createdAt: now,
            updatedAt: now,
          },
          {
            id: nanoid(),
            type: "activity",
            title: "Gelato at Giolitti",
            startTime: "16:30",
            duration: 30,
            location: {
              name: "Giolitti",
              address: "Via degli Uffici del Vicario, 40, 00186 Roma",
            },
            cost: {
              amount: 8,
              currency: "EUR",
            },
            notes: "Historic gelato shop. Try pistachio!",
            tags: ["dessert", "must-try"],
            links: [],
            status: "pending" as const,
            createdAt: now,
            updatedAt: now,
          },
          {
            id: nanoid(),
            type: "meal",
            title: "Dinner in Trastevere",
            startTime: "20:00",
            duration: 150,
            location: {
              name: "Trastevere neighborhood",
            },
            notes: "Walk around and pick a spot that looks good",
            tags: ["exploration"],
            links: [],
            status: "pending" as const,
            createdAt: now,
            updatedAt: now,
          },
        ],
      },
      {
        id: nanoid(),
        date: "2024-11-17",
        title: "Vatican & Beyond",
        cards: [
          {
            id: nanoid(),
            type: "activity",
            title: "Vatican Museums & Sistine Chapel",
            startTime: "08:30",
            duration: 240,
            location: {
              name: "Vatican Museums",
              address: "Viale Vaticano, 00165 Roma",
            },
            cost: {
              amount: 80,
              currency: "EUR",
            },
            notes:
              "Early entry tickets booked. Dress code: shoulders and knees covered.",
            tags: ["ticket-booked", "must-see", "early-entry"],
            links: ["https://biglietteriamusei.vatican.va/"],
            status: "confirmed" as const,
            createdAt: now,
            updatedAt: now,
          },
          {
            id: nanoid(),
            type: "activity",
            title: "St. Peter's Basilica",
            startTime: "13:00",
            duration: 90,
            location: {
              name: "St. Peter's Basilica",
              address: "Piazza San Pietro, 00120 Città del Vaticano",
            },
            notes: "Free entry. Consider climbing the dome ($10)",
            tags: ["free", "optional-upgrade"],
            links: [],
            status: "pending" as const,
            createdAt: now,
            updatedAt: now,
          },
          {
            id: nanoid(),
            type: "note",
            title: "Remember to bring power adapter",
            notes: "Type L (Italian) plug adapter needed for all electronics",
            tags: ["important", "todo"],
            links: [],
            status: "pending" as const,
            createdAt: now,
            updatedAt: now,
          },
        ],
      },
    ],
  };
}
